name: issue2docs
on: 
    issues: 
        types: [opened, edited]
    workflow_dispatch:
        
permissions:
    contents: write
jobs:
    transform:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: View the github context
              run: echo "$GITHUB_CONTEXT"
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
            - uses: actions/github-script@v7
              with:
                script: |
                    console.log(context)
                    console.log(context.payload.issue.title)
                    console.log(context.payload.issue.body)
                    console.log(context.payload.issue.created_at)
            - run: |
                  DEST="src/content/docs/reference/p-${{github.event.issue.id}}.md"
                  echo "DEST_MARKDOWN_FILE=$DEST" >> $GITHUB_ENV
            - uses: DamianReeves/write-file-action@master
              with:
                  path: ${{ env.DEST_MARKDOWN_FILE}}
                  contents: |
                      ---
                      title: ${{github.event.issue.title}}
                      description: ...
                      ---

                      ${{github.event.issue.body}}
                  write-mode: overwrite
            - uses: stefanzweifel/git-auto-commit-action@v5

