name: issue2docs
on: 
    issues: 
        types: [opened, edited]
permissions:
    contents: write
jobs:
    transform:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: View the github context
              run: echo "$GITHUB_CONTEXT"
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
            - run: |
                npm install @actions/exec
                npm install @actions/io
            - uses: actions/github-script@v7
              with:
                script: |
                    // console.log(context)
                    // console.log(context.payload.issue.title)
                    // console.log(context.payload.issue.body)
                    // console.log(context.payload.issue.created_at)
                    // don't work with output redirect
                    // const cmdRunner = require('@actions/exec');
                    // await cmdRunner.exec('echo "TEST_ENV_VAR=XXX" >> $GITHUB_ENV');
                    // exchange env vars between js and shell via writing to temp file 
                    const fs = require('fs')
                    fs.writeFileSync('./tmp_env', "TEST_ENV_VAR2=XXX")
            - run: |
                  DEST="src/content/docs/reference/p-${{github.event.issue.id}}.md"
                  echo "DEST_MARKDOWN_FILE=$DEST" >> $GITHUB_ENV
                  cat ./tmp_env >> $GITHUB_ENV
                  rm -rf ./tmp_env
                  echo $GITHUB_ENV
                  echo "$GITHUB_ENV"
                  cat $GITHUB_ENV
            - uses: DamianReeves/write-file-action@master
              with:
                  path: ${{ env.DEST_MARKDOWN_FILE}}
                  contents: |
                      ---
                      title: ${{github.event.issue.title}}
                      description: ...
                      ---

                      ${{github.event.issue.body}}

                      ${{env.TEST_ENV_VAR2}}
                  write-mode: overwrite
            - uses: stefanzweifel/git-auto-commit-action@v5

